name: CI Workflow

on:
  push:
  schedule:
    - cron: '0 1 * * *'

env:
  TESSDATA_PREFIX: /usr/share/tesseract-ocr/4.00/tessdata/
  CHROMEDRIVER_VERSION: 115.0.5790.102

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: atulnittcse/RnccSelenium
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip tesseract-ocr

        pip3 install selenium pytesseract pillow

        mkdir -p $HOME/drivers
        cd $HOME/drivers

        # Download and set up ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/${{ env.CHROMEDRIVER_VERSION }}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

        # Download and set up geckodriver (optional)
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xzf geckodriver-v0.33.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run pro.py
      id: pro
      continue-on-error: true
      run: python pro.py

    - name: Run sick.py
      id: sick
      continue-on-error: true
      run: python sick.py

    - name: Run newwarranty.py
      id: newwarranty
      continue-on-error: true
      run: python newwarranty.py

    - name: Check test result
      run: |
        if [ "${{ steps.pro.outcome }}" == "failure" ] || [ "${{ steps.sick.outcome }}" == "failure" ] || [ "${{ steps.newwarranty.outcome }}" == "failure" ]; then
          exit 1
        fi
