name: CI Workflow

on:
  push:
  schedule:
    - cron:  '0 1 * * *'

env:
  TESSDATA_PREFIX : /usr/share/tesseract-ocr/4.00/tessdata/


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: atulnittcse/RnccSelenium
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip tesseract-ocr

        pip3 install selenium pytesseract pillow

        mkdir -p $HOME/drivers
        cd $HOME/drivers

        wget https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver

        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xzf geckodriver-v0.33.0-linux64.tar.gz
        chmod +x geckodriver

        echo "$HOME/drivers" >> $GITHUB_PATH
        
    - name: Run pro.py
      id: pro
      continue-on-error: true
      run: python pro.py

    - name: Run sick.py
      id: sick
      continue-on-error: true
      run: python sick.py

    - name: Run newwarranty.py
      id: newwarranty
      continue-on-error: true
      run: python newwarranty.py

    - name: Check test result
      run: |
        if [ "${{ steps.pro.outcome }}" == "failure" ] || [ "${{ steps.sick.outcome }}" == "failure" ] || [ "${{ steps.newwarranty.outcome }}" == "failure" ]; then
          exit 1
        fi
