name: CI Workflow

on:
  push:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: atulnittcse/RnccSelenium
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
      
    - name: Setup Chrome, ChromeDriver and Tesseract
      run: |
        sudo apt-get update && \
        sudo apt-get install -y wget unzip tesseract-ocr tesseract-ocr-eng && \
        wget -N https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_linux64.zip -P ~/Downloads && \
        unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads && \
        sudo chmod +x ~/Downloads/chromedriver && \
        sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver && \
        sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver && \
        sudo wget -O /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata https://github.com/tesseract-ocr/tessdata/blob/main/eng.traineddata && \
        export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/


    - name: Run Maven install
      run: mvn clean install

    - name: Run Maven compile and exec
      run: mvn compile exec:java